# Generated by Django 4.0.4 on 2022-04-22 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(max_length=60, verbose_name='Code')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(help_text='Total that can be used', verbose_name='Quantity')),
                ('balance', models.PositiveIntegerField(help_text='The remaining discount codes', verbose_name='Balance')),
                ('brand', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discount', to='domain.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discount',
                'ordering': ['code'],
            },
        ),
    ]
