# Generated by Django 4.0.4 on 2022-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='balance',
        ),
        migrations.AlterField(
            model_name='discount',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_discount', to='domain.brand', verbose_name='Brand'),
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discount', to='domain.discount', verbose_name='Discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discount', to='domain.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Discount',
                'verbose_name_plural': 'User Discounts',
                'db_table': 'user_discount',
                'ordering': ['pk'],
            },
        ),
    ]
