kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: app-name
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWEowZFhKbmIyMXpPbWRvY0Y5YWVXODBkRUpVTlc1bFRtMWtZM2wzUzFkT09XOWxWbWx0VW5ZMFExQXlTblV4UVRBPSJ9fX0=

---

apiVersion: v1
data:
  DB_HOST: cG9zdGdyZXMtY2x1c3Rlci1pcC1zZXJ2aWNl
  DB_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: null
  name: pgbouncer-env
  namespace: default
